services:
  # Backend API Service
  - type: web
    name: acoustic-detection-api
    env: python
    buildCommand: |
      cd backend
      pip install -r requirements.txt
    startCommand: |
      cd backend
      python -m uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.6
      - key: PORT
        fromService:
          type: web
          name: acoustic-detection-api
          property: port

  # Frontend Static Site
  - type: static
    name: acoustic-detection-frontend
    buildCommand: |
      cd frontend
      npm install
      npm run build
    staticPublishPath: frontend/build
    envVars:
      - key: REACT_APP_API_URL
        fromService:
          type: web
          name: acoustic-detection-api
          property: host
